# Main Module Sucuri.
#
#.. codeauthor:: Carlo Oliveira <carlo@nce.ufrj.br>
#
#Changelog
#---------
#.. versionadded::    24.12
#   |br| Classes Head, Pane (10).
#
#|   **Open Source Notification:** This file is part of open source program **Pynoplia**
#|   **Copyright © 2024  Carlo Oliveira** <carlo@nce.ufrj.br>,
#|   **SPDX-License-Identifier:** `GNU General Public License v3.0 or later <http:#is.gd/3Udt>`_.
#|   `Labase <http:#labase.selfip.org/>`_ - `NCE <https:#portal.nce.ufrj.br>`_ - `UFRJ <https:#ufrj.br/>`_.
[Z0]
I1="VENICE GARDEN SOFT APRESENTA:"
I2="PRODUZIDO POR VENICE GARDEN SOFT"
[Z0.LCOZI]
D0="VOCE ESTA NA COZINHA DA VOVO"
[Z0.LCOZI.VABRA]
D0="ABRE GELADEIRA"
[Z1]
I1="VENICE GARDEN SOFT APRESENTA:"
[Z1.LSALA]
D0="VOCE ESTA NA SALA DA VOVO"
[Z1.LSALA.VABRA]
D0="ABRE PORTA"
